<?php
$route =session('dir_prefix','admin');
/*if(isset($_COOKIE['dir_prefix'])) {
    $route = $_COOKIE['dir_prefix'];
}
else
{

}*/

return [
    'vendor_dir'                 => env('VENDOR_DIR', 'vendor'),
    'admin_dir'                  => $route,
    //'admin_dir'                 => env('ADMIN_DIR', 'admin'),
    'default-theme'             => env('DEFAULT_THEME', 'default'),
    'base_name'                 => env('APP_NAME', 'Botble Technologies'),
    'logo'                      => '/vendor/core/core/base/images/logo_white.png',
    'favicon'                   => '/vendor/core/core/base/images/favicon.png',
    'editor'                    => [
        'ckeditor' => [
            'js' => [
                '/vendor/core/core/base/libraries/ckeditor/ckeditor.js',
            ],
        ],
        'tinymce'  => [
            'js' => [
                '/vendor/core/core/base/libraries/tinymce/tinymce.min.js',
            ],
        ],
        'primary'  => env('PRIMARY_EDITOR', 'ckeditor'),
    ],
    'error_reporting'           => [
        'to'           => null,
        'via_slack'    => env('SLACK_REPORT_ENABLED', false),
        'ignored_bots' => [
            'googlebot',        // Googlebot
            'bingbot',          // Microsoft Bingbot
            'slurp',            // Yahoo! Slurp
            'ia_archiver',      // Alexa
        ],
    ],
    'enable_https_support'      => env('ENABLE_HTTPS_SUPPORT', false),
    'date_format'               => [
        'date'      => 'Y-m-d',
        'date_time' => 'Y-m-d H:i:s',
        'js'        => [
            'date'      => 'yyyy-mm-dd',
            'date_time' => 'yyyy-mm-dd H:i:s',
        ],
    ],
    'cache_site_map'            => env('ENABLE_CACHE_SITE_MAP', false),
    'public_single_ending_url'  => env('PUBLIC_SINGLE_ENDING_URL'),
    'send_mail_using_job_queue' => env('SEND_MAIL_USING_JOB_QUEUE', false),
    'locale'                    => env('APP_LOCALE', 'en'),
    'can_execute_command'       => env('CAN_EXECUTE_COMMAND', true),
    'google_fonts'              => [
        'Aclonica',
        'Allan',
        'Annie Use Your Telescope',
        'Anonymous Pro',
        'Allerta Stencil',
        'Allerta',
        'Amaranth',
        'Anton',
        'Archivo',
        'Architects Daughter',
        'Arimo',
        'Artifika',
        'Arvo',
        'Asset',
        'Astloch',
        'Bangers',
        'Bentham',
        'Bevan',
        'Bigshot One',
        'Bowlby One',
        'Bowlby One SC',
        'Brawler',
        'Buda:300',
        'Cabin',
        'Calligraffitti',
        'Candal',
        'Cantarell',
        'Cardo',
        'Carter One',
        'Caudex',
        'Cedarville Cursive',
        'Cherry Cream Soda',
        'Chewy',
        'Coda',
        'Coming Soon',
        'Copse',
        'Corben:700',
        'Cousine',
        'Covered By Your Grace',
        'Crafty Girls',
        'Crimson Text',
        'Crushed',
        'Cuprum',
        'Damion',
        'Dancing Script',
        'Dawning of a New Day',
        'DM Sans',
        'Didact Gothic',
        'Droid Sans',
        'Droid Sans Mono',
        'Droid Serif',
        'EB Garamond',
        'Expletus Sans',
        'Fontdiner Swanky',
        'Forum',
        'Francois One',
        'Geo',
        'Give You Glory',
        'Goblin One',
        'Goudy Bookletter 1911',
        'Gravitas One',
        'Gruppo',
        'Hammersmith One',
        'Holtwood One SC',
        'Homemade Apple',
        'Inconsolata',
        'Indie Flower',
        'IM Fell DW Pica',
        'IM Fell DW Pica SC',
        'IM Fell Double Pica',
        'IM Fell Double Pica SC',
        'IM Fell English',
        'IM Fell English SC',
        'IM Fell French Canon',
        'IM Fell French Canon SC',
        'IM Fell Great Primer',
        'IM Fell Great Primer SC',
        'Irish Grover',
        'Irish Growler',
        'Istok Web',
        'Josefin Sans',
        'Josefin Slab',
        'Judson',
        'Jura',
        'Jura:500',
        'Jura:600',
        'Just Another Hand',
        'Just Me Again Down Here',
        'Kameron',
        'Kenia',
        'Kranky',
        'Kreon',
        'Kristi',
        'La Belle Aurore',
        'Lato:100',
        'Lato:100italic',
        'Lato:300',
        'Lato',
        'Lato:bold',
        'Lato:900',
        'League Script',
        'Lekton',
        'Limelight',
        'Lobster',
        'Lobster Two',
        'Lora',
        'Love Ya Like A Sister',
        'Loved by the King',
        'Luckiest Guy',
        'Maiden Orange',
        'Mako',
        'Maven Pro',
        'Maven Pro:500',
        'Maven Pro:700',
        'Maven Pro:900',
        'Meddon',
        'MedievalSharp',
        'Megrim',
        'Merriweather',
        'Metrophobic',
        'Michroma',
        'Miltonian Tattoo',
        'Miltonian',
        'Modern Antiqua',
        'Monofett',
        'Molengo',
        'Montserrat',
        'Mountains of Christmas',
        'Muli:300',
        'Muli',
        'Neucha',
        'Neuton',
        'News Cycle',
        'Nixie One',
        'Nobile',
        'Noto Sans',
        'Nova Cut',
        'Nova Flat',
        'Nova Mono',
        'Nova Oval',
        'Nova Round',
        'Nova Script',
        'Nova Slim',
        'Nova Square',
        'Nunito:light',
        'Nunito',
        'Nunito Sans',
        'OFL Sorts Mill Goudy TT',
        'Old Standard TT',
        'Open Sans:300',
        'Open Sans',
        'Open Sans:600',
        'Open Sans:800',
        'Open Sans Condensed:300',
        'Orbitron',
        'Orbitron:500',
        'Orbitron:700',
        'Orbitron:900',
        'Oswald',
        'Over the Rainbow',
        'Reenie Beanie',
        'Pacifico',
        'Patrick Hand',
        'Paytone One',
        'Permanent Marker',
        'Philosopher',
        'Play',
        'Playfair Display',
        'Podkova',
        'Poppins',
        'PT Sans',
        'PT Sans Narrow',
        'PT Sans Narrow:regular,bold',
        'PT Serif',
        'PT Serif Caption',
        'Puritan',
        'Quattrocento',
        'Quattrocento Sans',
        'Radley',
        'Raleway',
        'Raleway:100',
        'Redressed',
        'Rock Salt',
        'Rokkitt',
        'Roboto',
        'Roboto Condensed',
        'Roboto Slab',
        'Ruslan Display',
        'Schoolbell',
        'Shadows Into Light',
        'Shanti',
        'Sigmar One',
        'Six Caps',
        'Slackey',
        'Smythe',
        'Sniglet:800',
        'Special Elite',
        'Stardos Stencil',
        'Sue Ellen Francisco',
        'Sunshiney',
        'Swanky and Moo Moo',
        'Syncopate',
        'Tajawal',
        'Tangerine',
        'Tenor Sans',
        'Terminal Dosis Light',
        'The Girl Next Door',
        'Tinos',
        'Ubuntu',
        'Ultra',
        'Unkempt',
        'UnifrakturCook:bold',
        'UnifrakturMaguntia',
        'Varela',
        'Varela Round',
        'Vibur',
        'Vollkorn',
        'VT323',
        'Waiting for the Sunrise',
        'Wallpoet',
        'Walter Turncoat',
        'Wire One',
        'Work Sans',
        'Yanone Kaffeesatz',
        'Yanone Kaffeesatz:300',
        'Yanone Kaffeesatz:400',
        'Yanone Kaffeesatz:700',
        'Yeseva One',
        'Zeyada',
    ],

    'countries'                 => [
        'AF' => 'Afghanistan',
        'AX' => 'Åland Islands',
        'AL' => 'Albania',
        'DZ' => 'Algeria',
        'AS' => 'American Samoa',
        'AD' => 'Andorra',
        'AO' => 'Angola',
        'AI' => 'Anguilla',
        'AQ' => 'Antarctica',
        'AG' => 'Antigua and Barbuda',
        'AR' => 'Argentina',
        'AM' => 'Armenia',
        'AW' => 'Aruba',
        'AU' => 'Australia',
        'AT' => 'Austria',
        'AZ' => 'Azerbaijan',
        'BS' => 'Bahamas',
        'BH' => 'Bahrain',
        'BD' => 'Bangladesh',
        'BB' => 'Barbados',
        'BY' => 'Belarus',
        'BE' => 'Belgium',
        'PW' => 'Belau',
        'BZ' => 'Belize',
        'BJ' => 'Benin',
        'BM' => 'Bermuda',
        'BT' => 'Bhutan',
        'BO' => 'Bolivia',
        'BQ' => 'Bonaire, Saint Eustatius and Saba',
        'BA' => 'Bosnia and Herzegovina',
        'BW' => 'Botswana',
        'BV' => 'Bouvet Island',
        'BR' => 'Brazil',
        'IO' => 'British Indian Ocean Territory',
        'BN' => 'Brunei',
        'BG' => 'Bulgaria',
        'BF' => 'Burkina Faso',
        'BI' => 'Burundi',
        'KH' => 'Cambodia',
        'CM' => 'Cameroon',
        'CA' => 'Canada',
        'CV' => 'Cape Verde',
        'KY' => 'Cayman Islands',
        'CF' => 'Central African Republic',
        'TD' => 'Chad',
        'CL' => 'Chile',
        'CN' => 'China',
        'CX' => 'Christmas Island',
        'CC' => 'Cocos (Keeling) Islands',
        'CO' => 'Colombia',
        'KM' => 'Comoros',
        'CG' => 'Congo (Brazzaville)',
        'CD' => 'Congo (Kinshasa)',
        'CK' => 'Cook Islands',
        'CR' => 'Costa Rica',
        'HR' => 'Croatia',
        'CU' => 'Cuba',
        'CW' => 'Cura&ccedil;ao',
        'CY' => 'Cyprus',
        'CZ' => 'Czech Republic',
        'DK' => 'Denmark',
        'DJ' => 'Djibouti',
        'DM' => 'Dominica',
        'DO' => 'Dominican Republic',
        'EC' => 'Ecuador',
        'EG' => 'Egypt',
        'SV' => 'El Salvador',
        'GQ' => 'Equatorial Guinea',
        'ER' => 'Eritrea',
        'EE' => 'Estonia',
        'ET' => 'Ethiopia',
        'FK' => 'Falkland Islands',
        'FO' => 'Faroe Islands',
        'FJ' => 'Fiji',
        'FI' => 'Finland',
        'FR' => 'France',
        'GF' => 'French Guiana',
        'PF' => 'French Polynesia',
        'TF' => 'French Southern Territories',
        'GA' => 'Gabon',
        'GM' => 'Gambia',
        'GE' => 'Georgia',
        'DE' => 'Germany',
        'GH' => 'Ghana',
        'GI' => 'Gibraltar',
        'GR' => 'Greece',
        'GL' => 'Greenland',
        'GD' => 'Grenada',
        'GP' => 'Guadeloupe',
        'GU' => 'Guam',
        'GT' => 'Guatemala',
        'GG' => 'Guernsey',
        'GN' => 'Guinea',
        'GW' => 'Guinea-Bissau',
        'GY' => 'Guyana',
        'HT' => 'Haiti',
        'HM' => 'Heard Island and McDonald Islands',
        'HN' => 'Honduras',
        'HK' => 'Hong Kong',
        'HU' => 'Hungary',
        'IS' => 'Iceland',
        'IN' => 'India',
        'ID' => 'Indonesia',
        'IR' => 'Iran',
        'IQ' => 'Iraq',
        'IE' => 'Ireland',
        'IM' => 'Isle of Man',
        'IL' => 'Israel',
        'IT' => 'Italy',
        'CI' => 'Ivory Coast',
        'JM' => 'Jamaica',
        'JP' => 'Japan',
        'JE' => 'Jersey',
        'JO' => 'Jordan',
        'KZ' => 'Kazakhstan',
        'KE' => 'Kenya',
        'KI' => 'Kiribati',
        'KW' => 'Kuwait',
        'XK' => 'Kosovo',
        'KG' => 'Kyrgyzstan',
        'LA' => 'Laos',
        'LV' => 'Latvia',
        'LB' => 'Lebanon',
        'LS' => 'Lesotho',
        'LR' => 'Liberia',
        'LY' => 'Libya',
        'LI' => 'Liechtenstein',
        'LT' => 'Lithuania',
        'LU' => 'Luxembourg',
        'MO' => 'Macao',
        'MK' => 'North Macedonia',
        'MG' => 'Madagascar',
        'MW' => 'Malawi',
        'MY' => 'Malaysia',
        'MV' => 'Maldives',
        'ML' => 'Mali',
        'MT' => 'Malta',
        'MH' => 'Marshall Islands',
        'MQ' => 'Martinique',
        'MR' => 'Mauritania',
        'MU' => 'Mauritius',
        'YT' => 'Mayotte',
        'MX' => 'Mexico',
        'FM' => 'Micronesia',
        'MD' => 'Moldova',
        'MC' => 'Monaco',
        'MN' => 'Mongolia',
        'ME' => 'Montenegro',
        'MS' => 'Montserrat',
        'MA' => 'Morocco',
        'MZ' => 'Mozambique',
        'MM' => 'Myanmar',
        'NA' => 'Namibia',
        'NR' => 'Nauru',
        'NP' => 'Nepal',
        'NL' => 'Netherlands',
        'NC' => 'New Caledonia',
        'NZ' => 'New Zealand',
        'NI' => 'Nicaragua',
        'NE' => 'Niger',
        'NG' => 'Nigeria',
        'NU' => 'Niue',
        'NF' => 'Norfolk Island',
        'MP' => 'Northern Mariana Islands',
        'KP' => 'North Korea',
        'NO' => 'Norway',
        'OM' => 'Oman',
        'PK' => 'Pakistan',
        'PS' => 'Palestinian Territory',
        'PA' => 'Panama',
        'PG' => 'Papua New Guinea',
        'PY' => 'Paraguay',
        'PE' => 'Peru',
        'PH' => 'Philippines',
        'PN' => 'Pitcairn',
        'PL' => 'Poland',
        'PT' => 'Portugal',
        'PR' => 'Puerto Rico',
        'QA' => 'Qatar',
        'RE' => 'Reunion',
        'RO' => 'Romania',
        'RU' => 'Russia',
        'RW' => 'Rwanda',
        'BL' => 'Saint Barth&eacute;lemy',
        'SH' => 'Saint Helena',
        'KN' => 'Saint Kitts and Nevis',
        'LC' => 'Saint Lucia',
        'MF' => 'Saint Martin (French part)',
        'SX' => 'Saint Martin (Dutch part)',
        'PM' => 'Saint Pierre and Miquelon',
        'VC' => 'Saint Vincent and the Grenadines',
        'SM' => 'San Marino',
        'ST' => 'S&atilde;o Tom&eacute; and Pr&iacute;ncipe',
        'SA' => 'Saudi Arabia',
        'SN' => 'Senegal',
        'RS' => 'Serbia',
        'SC' => 'Seychelles',
        'SL' => 'Sierra Leone',
        'SG' => 'Singapore',
        'SK' => 'Slovakia',
        'SI' => 'Slovenia',
        'SB' => 'Solomon Islands',
        'SO' => 'Somalia',
        'ZA' => 'South Africa',
        'GS' => 'South Georgia/Sandwich Islands',
        'KR' => 'South Korea',
        'SS' => 'South Sudan',
        'ES' => 'Spain',
        'LK' => 'Sri Lanka',
        'SD' => 'Sudan',
        'SR' => 'Suriname',
        'SJ' => 'Svalbard and Jan Mayen',
        'SZ' => 'Swaziland',
        'SE' => 'Sweden',
        'CH' => 'Switzerland',
        'SY' => 'Syria',
        'TW' => 'Taiwan',
        'TJ' => 'Tajikistan',
        'TZ' => 'Tanzania',
        'TH' => 'Thailand',
        'TL' => 'Timor-Leste',
        'TG' => 'Togo',
        'TK' => 'Tokelau',
        'TO' => 'Tonga',
        'TT' => 'Trinidad and Tobago',
        'TN' => 'Tunisia',
        'TR' => 'Turkey',
        'TM' => 'Turkmenistan',
        'TC' => 'Turks and Caicos Islands',
        'TV' => 'Tuvalu',
        'UG' => 'Uganda',
        'UA' => 'Ukraine',
        'AE' => 'United Arab Emirates',
        'GB' => 'United Kingdom (UK)',
        'US' => 'United States (US)',
        'UM' => 'United States (US) Minor Outlying Islands',
        'UY' => 'Uruguay',
        'UZ' => 'Uzbekistan',
        'VU' => 'Vanuatu',
        'VA' => 'Vatican',
        'VE' => 'Venezuela',
        'VN' => 'Vietnam',
        'VG' => 'Virgin Islands (British)',
        'VI' => 'Virgin Islands (US)',
        'WF' => 'Wallis and Futuna',
        'EH' => 'Western Sahara',
        'WS' => 'Samoa',
        'YE' => 'Yemen',
        'ZM' => 'Zambia',
        'ZW' => 'Zimbabwe',
    ],
    'cities'                 => [
        'Abbottabad' => 'Abbottabad',
        'Adezai' => 'Adezai',
        'Ahmadpur East' => 'Ahmadpur East',
        'Ahmed Nager Chatha' => 'Ahmed Nager Chatha',
        'Akora Khattak' => 'Akora Khattak',
        'Ali Khan Abad' => 'Ali Khan Abad',
        'Alipur' => 'Alipur',
        'Alpuri' => 'Alpuri',
        'Arifwala' => 'Arifwala',
        'Attock' => 'Attock',
        'Awaran' => 'Awaran',
        'Ayubia' => 'Ayubia',
        'Badin' => 'Badin',
        'Bahawalnagar' => 'Bahawalnagar',
        'Bahawalpur' => 'Bahawalpur',
        'Banda Daud Shah' => 'Banda Daud Shah',
        'Bannu' => 'Bannu',
        'Barkhan' => 'Barkhan',
        'Batkhela' => 'Batkhela',
        'Battagram' => 'Battagram',
        'Bhakkar' => 'Bhakkar',
        'Bhalwal' => 'Bhalwal',
        'Bhera' => 'Bhera',
        'Bhirkan' => 'Bhirkan',
        'Birote' => 'Birote',
        'Burewala' => 'Burewala',
        'Chagai' => 'Chagai',
        'Chak' => 'Chak',
        'Chakdara' => 'Chakdara',
        'Chakwal' => 'Chakwal',
        'Charsadda' => 'Charsadda',
        'Chichawatni' => 'Chichawatni',
        'Chillianwala' => 'Chillianwala',
        'Chiniot' => 'Chiniot',
        'Chishtian' => 'Chishtian',
        'Chitral' => 'Chitral',
        'Dadu' => 'Dadu',
        'Daggar' => 'Daggar',
        'Dargai' => 'Dargai',
        'Darya Khan' => 'Darya Khan',
        'Daska' => 'Daska',
        'Dera Bugti' => 'Dera Bugti',
        'Dera Ghazi Khan' => 'Dera Ghazi Khan',
        'Dera Ismail Khan' => 'Dera Ismail Khan',
        'Dhaular' => 'Dhaular',
        'Digri' => 'Digri',
        'Dina' => 'Dina',
        'Dinga' => 'Dinga',
        'Dipalpur' => 'Dipalpur',
        'Diplo' => 'Diplo',
        'Dir' => 'Dir',
        'Doaba' => 'Doaba',
        'Dokri' => 'Dokri',
        'Drosh' => 'Drosh',
        'Faisalabad' => 'Faisalabad',
        'Fateh Jhang' => 'Fateh Jhang',
        'Ferozewala' => 'Ferozewala',
        'Ghakhar Mandi' => 'Ghakhar Mandi',
        'Ghotki' => 'Ghotki',
        'Gojra' => 'Gojra',
        'Gujar Khan' => 'Gujar Khan',
        'Gujranwala' => 'Gujranwala',
        'Gujrat' => 'Gujrat',
        'Gwadar' => 'Gwadar',
        'Haala' => 'Haala',
        'Hafizabad' => 'Hafizabad',
        'Hangu' => 'Hangu',
        'Haripur' => 'Haripur',
        'Harnai' => 'Harnai',
        'Haroonabad' => 'Haroonabad',
        'Hasilpur' => 'Hasilpur',
        'Haveli Lakha' => 'Haveli Lakha',
        'Hyderabad' => 'Hyderabad',
        'Islamabad' => 'Islamabad',
        'Islamkot' => 'Islamkot',
        'Jacobabad' => 'Jacobabad',
        'Jafarabad' => 'Jafarabad',
        'Jalalpur' => 'Jalalpur',
        'Jampur' => 'Jampur',
        'Jamshoro' => 'Jamshoro',
        'Jaranwala' => 'Jaranwala',
        'Jatoi' => 'Jatoi',
        'Jattan' => 'Jattan',
        'Jauharabad' => 'Jauharabad',
        'Jhal Magsi' => 'Jhal Magsi',
        'Jhang' => 'Jhang',
        'Jhelum' => 'Jhelum',
        'Jungshahi' => 'Jungshahi',
        'Kacchi' => 'Kacchi',
        'Kalabagh' => 'Kalabagh',
        'Kalat' => 'Kalat',
        'Kamalia' => 'Kamalia',
        'Kamoke' => 'Kamoke',
        'Kandhkot' => 'Kandhkot',
        'Kandiaro' => 'Kandiaro',
        'Karachi' => 'Karachi',
        'Karak' => 'Karak',
        'Karor Lal Esan' => 'Karor Lal Esan',
        'Kashmore' => 'Kashmore',
        'Kasur' => 'Kasur',
        'Kech' => 'Kech',
        'Keti Bandar' => 'Keti Bandar',
        'Khairpur' => 'Khairpur',
        'Khanewal' => 'Khanewal',
        'Khanpur' => 'Khanpur',
        'Kharan' => 'Kharan',
        'Kharian' => 'Kharian',
        'Khushab' => 'Khushab',
        'Khuzdar' => 'Khuzdar',
        'Killa Abdullah' => 'Killa Abdullah',
        'Killa Saifullah' => 'Killa Saifullah',
        'Kohat' => 'Kohat',
        'Kohlu' => 'Kohlu',
        'Kot Addu' => 'Kot Addu',
        'Kotri' => 'Kotri',
        'Kulachi' => 'Kulachi',
        'Lahore' => 'Lahore',
        'Lakki Marwat' => 'Lakki Marwat',
        'Lalamusa' => 'Lalamusa',
        'Larkana' => 'Larkana',
        'Lasbela' => 'Lasbela',
        'Latamber' => 'Latamber',
        'Layyah' => 'Layyah',
        'Lehri' => 'Lehri',
        'Liaquat Pur' => 'Liaquat Pur',
        'Lodhran' => 'Lodhran',
        'Loralai' => 'Loralai',
        'Madyan' => 'Madyan',
        'Mailsi' => 'Mailsi',
        'Malakwal' => 'Malakwal',
        'Mamoori' => 'Mamoori',
        'Mandi Bahauddin' => 'Mandi Bahauddin',
        'Mansehra' => 'Mansehra',
        'Mardan' => 'Mardan',
        'Mastuj' => 'Mastuj',
        'Mastung' => 'Mastung',
        'Matiari' => 'Matiari',
        'Mehar' => 'Mehar',
        'Mehrabpur' => 'Mehrabpur',
        'Mian Channu' => 'Mian Channu',
        'Mianwali' => 'Mianwali',
        'Mianwali Bangla' => 'Mianwali Bangla',
        'Mingora' => 'Mingora',
        'Mirpur Khas' => 'Mirpur Khas',
        'Mithani' => 'Mithani',
        'Mithi' => 'Mithi',
        'Moro' => 'Moro',
        'Multan' => 'Multan',
        'Muridke' => 'Muridke',
        'Murree' => 'Murree',
        'Musakhel' => 'Musakhel',
        'Muzaffargarh' => 'Muzaffargarh',
        'Nagarparkar' => 'Nagarparkar',
        'Nankana Sahib' => 'Nankana Sahib',
        'Narowal' => 'Narowal',
        'Nasirabad' => 'Nasirabad',
        'Naudero' => 'Naudero',
        'Naushahro Feroze' => 'Naushahro Feroze',
        'Naushara' => 'Naushara',
        'Nawabshah' => 'Nawabshah',
        'Nazimabad' => 'Nazimabad',
        'Nowshera' => 'Nowshera',
        'Nushki' => 'Nushki',
        'Okara' => 'Okara',
        'Pabbi' => 'Pabbi',
        'Paharpur' => 'Paharpur',
        'Pakpattan' => 'Pakpattan',
        'Panjgur' => 'Panjgur',
        'Pattoki' => 'Pattoki',
        'Peshawar' => 'Peshawar',
        'Pir Mahal' => 'Pir Mahal',
        'Pishin Valley' => 'Pishin Valley',
        'Qaimpur' => 'Qaimpur',
        'Qambar' => 'Qambar',
        'Qasimabad' => 'Qasimabad',
        'Qila Didar Singh' => 'Qila Didar Singh',
        'Quetta' => 'Quetta',
        'Rabwah' => 'Rabwah',
        'Rahim Yar Khan' => 'Rahim Yar Khan',
        'Raiwind' => 'Raiwind',
        'Rajanpur' => 'Rajanpur',
        'Rajo Khanani' => 'Rajo Khanani',
        'Ranipur' => 'Ranipur',
        'Ratodero' => 'Ratodero',
        'Rawalpindi' => 'Rawalpindi',
        'Renala Khurd' => 'Renala Khurd',
        'Rohri' => 'Rohri',
        'Sadiqabad' => 'Sadiqabad',
        'Safdarabad' => 'Safdarabad',
        'Sahiwal' => 'Sahiwal',
        'Saidu Sharif' => 'Saidu Sharif',
        'Sakrand' => 'Sakrand',
        'Sanghar' => 'Sanghar',
        'Sangla Hill' => 'Sangla Hill',
        'Sarai Alamgir' => 'Sarai Alamgir',
        'Sargodha' => 'Sargodha',
        'Shahbandar' => 'Shahbandar',
        'Shahdadkot' => 'Shahdadkot',
        'Shahdadpur' => 'Shahdadpur',
        'Shahpur Chakar' => 'Shahpur Chakar',
        'Shakargarh' => 'Shakargarh',
        'Sheikhupura' => 'Sheikhupura',
        'Sherani' => 'Sherani',
        'Shewa Adda' => 'Shewa Adda',
        'Shikarpaur' => 'Shikarpaur',
        'Shorkot' => 'Shorkot',
        'Sialkot' => 'Sialkot',
        'Sibi' => 'Sibi',
        'Siranwali' => 'Siranwali',
        'Sohawa' => 'Sohawa',
        'Sohbatpur' => 'Sohbatpur',
        'Soianwala' => 'Soianwala',
        'Sukkur' => 'Sukkur',
        'Swabi' => 'Swabi',
        'Swat' => 'Swat',
        'Talagang' => 'Talagang',
        'Tando Adam Khan' => 'Tando Adam Khan',
        'Tando Allahyar' => 'Tando Allahyar',
        'Tando Muhammad Khan' => 'Tando Muhammad Khan',
        'Tangi' => 'Tangi',
        'Tangwani' => 'Tangwani',
        'Tank' => 'Tank',
        'Taxila' => 'Taxila',
        'Thall' => 'Thall',
        'Thatta' => 'Thatta',
        'Timergara' => 'Timergara',
        'Toba Tek Singh' => 'Toba Tek Singh',
        'Tordher' => 'Tordher',
        'Umerkot' => 'Umerkot',
        'Vehari' => 'Vehari',
        'Wah Cantonment' => 'Wah Cantonment',
        'Warah' => 'Warah',
        'Washuk' => 'Washuk',
        'Wazirabad' => 'Wazirabad',
        'Zhob' => 'Zhob',
        'Ziarat' => 'Ziarat',
        'Other'  => 'Other'
    ]
];
